services:
  exp.db.keycloak:
      image: postgres:alpine

  exp.keycloak.server:
      image: quay.io/keycloak/keycloak:26.3.4


  exp.keycloak.identityserver:
    image: ${DOCKER_REGISTRY-}keycloakidentityserver
    build:
      context: .
      dockerfile: Keycloak.IdentityServer/Dockerfile
